- name: Install firewalld
  package:
    name: "ufw"
    state: present

- name: Start firewalld
  service:
    name: ufw
    state: started

- name: Enable ufw
  ufw:
    state: enabled

- name: Open HTTP port on Ubuntu
  ufw:
    rule: allow
    port: "{{ web_port }}"
    proto: tcp

- name: Install apache
  package:
    name: "{{ package }}"
    state: present
  notify: Restart httpd