- name: Install firewalld
  package:
    name: "ufw"
    state: present

- name: Start firewalld
  service:
    name: ufw
    state: started

- name: Open port
  ufw:
    port: "{{ web_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true

- name: Install apache
  package:
    name: "{{ package }}"
    state: present
  notify: Restart httpd